#!/bin/bash

file="./teste.txt"
echo -e "; Generated by DualShock3_ubuntu_install
; Configs to Sony DualShock 3
; Player 1 Input
; Input Device: 0 = Unplugged, 1 = KEYBOARD/GAMEPAD
pl1contrl=1
; Keys for Select, Start, Up, Down, Left, Right, circle, X, square, triangle, L1, L2
pl1selk=310
pl1startk=313
pl1upk=314
pl1downk=316
pl1leftk=317
pl1rightk=315
pl1Xk=322
pl1Ak=323
pl1Lk=320
pl1Yk=325
pl1Bk=324
pl1Rk=321" > $file
