#!/bin/bash
set -x
zinput="~/.zsnes/zinput.cfg"
option="$1"

pause() {
	read -n 1 -p "Press any key to continue..." ; echo
}
# Preparing the environment
ds3_inst() {
	if [ $(id -u) != 0 ]; then exit 1; fi
	apt-add-repository ppa:falk-t-j/qtsixa
	apt-get update && apt-get -y install sixad libusb-dev libusb-0.1-4 bluez-utils
}
# Pairing function
ds3_conn() {
	echo 'Please connect the DualShock 3.' ; pause
	sixpair
	echo 'Please Disconnect the DualShock 3.' ; pause
	sixad --start
}
ds3_zsnes() {
echo -e "; Generated by DualShock3_ubuntu_install
; Configs to Sony DualShock 3
; Player 1 Input
; Input Device: 0 = Unplugged, 1 = KEYBOARD/GAMEPAD
pl1contrl=1
; Keys for Select, Start, Up, Down, Left, Right, circle, X, square, triangle, L1, L2
pl1selk=310
pl1startk=313
pl1upk=314
pl1downk=316
pl1leftk=317
pl1rightk=315
pl1Xk=322
pl1Ak=323
pl1Lk=320
pl1Yk=325
pl1Bk=324
pl1Rk=321" > $zinput
}
case $option in
	install) ds3_inst ;;
	pair) ds3_conn ;;
	zsnes) ds3_zsnes ;;
	*) echo "Type: pair or zsnes" ;;
esac
